apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15.0
          ports:
            - containerPort: 5432
          envFrom:
          - configMapRef:
              name: postgres-config
          - secretRef:
              name: postgres-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "kubenews"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: "a3ViZW5ld3M=" # POSTGRES_USER:      "kubenews"  | in base64
  POSTGRES_PASSWORD: "UGcjMTIz" # POSTGRES_PASSWORD:  "Pg#123"    | in base64
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
        - name: kubenews
          image: haaragard/kube-news:v1
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: kubenews-secret
---
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
  - name: http
    port: 80
    targetPort: 8080
    appProtocol: TCP
    nodePort: 30000
  type: NodePort
---
 apiVersion: v1
 kind: Secret
 metadata:
   name: kubenews-secret
 type: Opaque
 data:
   DB_HOST: "cG9zdGdyZXNxbA=="  # DB_HOST:      "postgresql"  | in base64
   DB_DATABASE: "a3ViZW5ld3M="  # DB_DATABASE:  "kubenews"    | in base64
   DB_USERNAME: "a3ViZW5ld3M="  # DB_USERNAME:  "kubenews"    | in base64
   DB_PASSWORD: "UGcjMTIz"      # DB_PASSWORD:  "Pg#123"      | in base64
